"""s1 users table auth D-19

Revision ID: 1aef6233c6ac
Revises: 53a8d21ecbe9
Create Date: 2026-07-18 03:09:51.390223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aef6233c6ac'
down_revision: Union[str, Sequence[str], None] = '53a8d21ecbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # id server_default gen_random_uuid(): INSERT raw (psycopg2 seed/audit) không cần điền id.
    # SQLAlchemy default=uuid4 là app-side, KHÔNG áp cho INSERT raw → phải có DB default.
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('pass_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
