"""s2 legal tables T2-2

Revision ID: 1ec70b10a031
Revises: b6a3c9659a20
Create Date: 2026-07-18 05:45:54.203487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec70b10a031'
down_revision: Union[str, Sequence[str], None] = 'b6a3c9659a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collateral_legal',
    sa.Column('collateral_id', sa.String(), nullable=False),
    sa.Column('dispute_status', sa.Text(), nullable=True),
    sa.Column('zoning_status', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('collateral_id')
    )
    op.create_table('legal_requirements',
    sa.Column('loan_type', sa.Text(), nullable=False),
    sa.Column('doc_code', sa.Text(), nullable=False),
    sa.Column('doc_name', sa.Text(), nullable=True),
    sa.Column('mandatory', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loan_type', 'doc_code')
    )
    op.create_table('owner_documents',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('doc_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id', 'doc_code')
    )
    op.create_table('restricted_purposes',
    sa.Column('purpose_code', sa.Text(), nullable=False),
    sa.Column('purpose_name', sa.Text(), nullable=True),
    sa.Column('restriction', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('purpose_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricted_purposes')
    op.drop_table('owner_documents')
    op.drop_table('legal_requirements')
    op.drop_table('collateral_legal')
    # ### end Alembic commands ###
