"""s1 server_default uuid ops tables D-28c

Revision ID: 448101c1915d
Revises: 1aef6233c6ac
Create Date: 2026-07-18 03:21:33.228050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448101c1915d'
down_revision: Union[str, Sequence[str], None] = '1aef6233c6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
