"""s3 approvals table T3-1

Revision ID: 8e8edc5b9187
Revises: 1ec70b10a031
Create Date: 2026-07-18 07:35:55.309531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e8edc5b9187'
down_revision: Union[str, Sequence[str], None] = '1ec70b10a031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conv_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('decided_by', sa.Text(), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('receipt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_conv_id'), 'approvals', ['conv_id'], unique=False)
    # composite index cho lookup key wrapper gated (conv_id, action, payload_hash) — 4 bước phanh
    op.create_index(
        "ix_approvals_key", "approvals", ["conv_id", "action", "payload_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approvals_key", table_name="approvals")
    op.drop_index(op.f('ix_approvals_conv_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
